* 实操
>20181219
买入阿里巴巴 139
>20200225
买入Facebook 200
>20200513
买入陌陌 21
>20200617
出阿里巴巴 224
策略
看巴菲特、高瓴资本等投资了哪些公司，低价时买入。
看<<中国企业家>>选中的未来之星。
买入一个股票，就要愿意持有3年以上，否则别买。
备选公司
微软、苹果、谷歌、美团、英伟达、特斯拉
================
20200520
skype、msn当年和QQ齐名，没想到被微软玩得这么惨。
skype核心是视频通讯，结果微软收购后，不紧抓这点，反而追求功能重新，丢了核心，让后起之秀zoom在视频通讯领域发展起来。
 
* 思想
不要看过去怎么样, 看未来怎么样。
不要看手里的股票能不能涨回去, 看目前了解的股票，哪个更有增长势头

不明资金来源的公司，不要碰！
管理层容易头脑发热的公司，不要碰！

有负面消息的股票，立即抛，可以跌了再买入。
** 自动化
公司、产品的关键词，和负面关键词一起出现的概率大幅提高
如: 英伟达  
*** 负面关键词
缺陷 暴跌 用户愤怒 业绩不佳 避而不谈 蒸发 凉了 倒霉 不及预期 下调 破发 齐降 重挫 放缓
抛售 累跌 调低 丑闻 麻烦缠身
* 战略、股票分析:股票涨跌幅分析(如1月、半年、1年的涨跌幅比较)
100 for each item.
weight for each item is different

** market    0.30
*** AI
无人驾驶

** team       0.25
*** CEO
蠢事做得多的人不能投。如: 人人网陈一舟，势利眼，对人的基本的尊重都没有。
好人，谨慎投。这个世界，好人难成大事。

main members

** data
>outcome    0.20
products
users
DAU/MAU

>price history   0.15

>news      0.10
*** 招聘信息

* 公司
** 拼多多
曹政、冯大辉都在以行动和自身影响力大力推荐拼多多股票。
我自己也从习惯在jd购物，两周内变成了习惯在拼多多购物，基本每两天一购，频率比在jd时高很多。
pdd市值到1200亿美金，1年内不是问题。
** fb
充分商业化的产品:WhatsApp

*** 1810
遭数据泄露
欧洲各国拟征收数字税

*** 1811
今年以来，Facebook已经有十多位高管离职，五月份，扎克伯格也对管理层进行了大调整。
除了大量高管离职之外，扎克伯格的风格也让员工士气十分低落。

被 Facebook 收购后，Instagram两位创始人 Kevin Systrom 和 Mike Krieger 不久前宣布离开这家公司，现在又有两位 Instagram 高管宣布离职。据彭博社报道，Instagram 已经在公司内部确认增长主管 Bangaly Kaba 和负责产品运营的 Ameet Ranadive 已经离职。

Instagram在内部以不加密的明文方式保存了密码，才会发生这样的错误，而不加密保存是安全行业并不推荐的做法。

美国舆论指出，Facebook现有的管理层已经不值得信任。外部民调也表明消费者对于Facebook的信任度已经垫底。

桑德伯格后来向朋友吐露说，这次交流使她惊慌失措，她不知道是否应该为自己的工作担心。

在保护个人数据方面，Facebook是美国最「不受待见」的明星科技巨头。只有22%的受访者说他们信任Facebook，远远低于亚马逊(49%)、谷歌(41%)、微软(40%)和苹果(39%)。

48%的受访者觉得Facebook比6个月前更加负面，只有17%的人看法朝正面发展。

美媒用三个词语总结了Facebook的危机公关应对策略，不是直接解决问题，而是「delay, deny and deflect」，即拖延、否认、转移。最近请公关公司写黑稿的事，扎克伯格和桑德伯格又异口同声的说，这事我们没听过，是公司公关团队做出的决定。桑德伯格这番言论直接激怒了公司相关团队成员，你是COO，我们向你汇报工作，你居然说跟你没关系，直接把锅推给我们？不得已，上周五，桑德伯格在内部会议上表示：她对公关部门所有行动负全责。

因为创始人的天花板，很多时候就是企业发展的天花板。

** 腾讯
          | 应用宝0719       |
 微信     | 70亿(330376评论) |
 QQ       | 79亿(351440评论) |
 王者荣耀 | 8.8亿            |
 绝地求生 | 1亿(37231评论)   |
          |                  |
*** 1810
戏被监管
间被头条分走

构变革
司回购



*** 1811
低游戏预算
18年第三季度财报:用户增长停滞; 游戏收入受政策影响严重

程序日活2亿
腾讯的根基没有受到冲击，反而在多方面展现较强生命力。

社交产品“后院灭火”之后，马化腾决定再给深陷失败漩涡的游戏一个机会。他把业务交到任宇昕手中，并特意为腾讯游戏的队伍搭建开绿灯，让他随意挑选公司内部人才。
任宇昕为腾讯游戏确定了清晰的组织架构，其主导的工作室制度被IEG（互动娱乐事业群）沿用至今。在战略方向上，他选择从品类简单的休闲游戏切入，只用不到两年就超越鲍岳桥的联众，随后腾讯介入大型游戏领域，又用两年时间将盛大从榜首位置拉下，自己取而代之。
*** 202002
微信支付19年取得突出成绩，获得创始人奖。

** 头条
   | 抖音 |
   |   |
   |   |
** amazon
*** 1811
至于方法，就是持续「聚焦于顾客」，而不是向内看。
如果我们开始将注意力放在我们自己身上，而不是关注顾客，那就是亚马逊走向终结的开始。
贝索斯思维的核心：非共识

彼得·蒂尔在《从0到1》说过一句话：
每当我面试应聘者时，都会问这样一个问题：在什么重要问题上，你与其他人有不同看法？好的回答是这种模式：大多数人相信 x，但事实却是 x 的对立面。

在我们452个目标中，“净收入”、“毛利润”和“运营利润”等字眼一次也没出现。
—— 杰夫·贝索斯 《2009年致股东信》

贝索斯说，公司的估值不是按利润来算的，而是按照自由现金流 × 倍数。
为什么是自由现金流？
自由现金流是什么？一个企业在满足了运营成本和维护性资本开支之后，可以自由分配的钱。

Netflix 的创始人说，一个公司账上的现金越多，说明这个公司的创新动力越不足。

所有只能产生短期利润的项目都不重要，无论现在赚多少钱；
能够产生长期现金流的项目才是重要的，无论现在亏多少钱！

他反对竞争对手中心论，称：
不要管竞争对手在做什么，他们又不给你钱。
事实也的确如此，如果贝索斯整天盯着 Ebay，他不可能做出 AWS 云服务；

如果你做的每一件事把眼光放到未来三年，和你同台竞技的人很多；但是如果你的目光能放到未来七年，那么可以和你竞争的就很少了，因为很少有公司愿意做那么长远的打算。
—— 杰夫·贝索斯（2011年）

贝索斯说：
我经常被问到一个问题：“未来十年，会有什么样的变化？”但我很少被问到：“未来十年，什么是不变的？”
我认为第二个问题比第一个问题更重要，因为你需要将你的战略建立在不变的事物上。

当时，最反对的人是他的 CFO，这个 CFO 非常有战斗力，是贝索斯的战友，但在这个项目上，那个 CFO 说，免费送货不是什么创举，只是让我们未来的资产负债表再一次出问题。有一次开会，他甚至让提供这个建议的人降职。
目前，Prime全球会员数已经超过 9000 万，按照每人每年 99 美元的会费计算，这笔收入将近 90 亿美元，但迄今为止这个项目还是亏损的，亚马逊在 Prime 权益上的投入远超过这个数字。
但回头看，99 美元年费刺激了会员充分利用 Prime 价值的心理，下了更多的订单，大量顾客因为这个服务成为亚马逊的拥趸。
这被认为是亚马逊历史上最划算的买卖之一。

任何组织随着时间的推移，一定会变得涣散化、官僚化、失效化并最终走向死亡，这中间最大的力量就是因为组织的熵增。
** 英伟达
*** 1811
数据中心和自动驾驶一直都是支撑英伟达人工智能信仰的重要业务。因为他们都是人工智能领域里最落地的商业场景。但是，从最新一季的财报显示，数据中心的增长数据在放缓，而自动驾驶大规模增长的时间点还未来到。 


** 阿里
*** 团队
**** 张勇
只有敢做别人不敢做的决定、敢承担别人不敢承担的责任、能搞定别人搞不定的资源的人才是老大。
骨子里，张勇和马云是一种人：雄心志四海、万里望风尘。
他已经看到B2C是未来的大趋势，不能眼看着它死掉，让阿里错过这个风口。

阿里员工评价张勇：拥有敏锐的商业嗅觉，往往能一眼看出产品的痛点。他这个“临时工”不仅很快带领淘宝商城走上正轨，还发明了以后深刻改变中国和世界购物习惯的“双11”购物节。

“淘宝商城”改名为“天猫”，英文名“Tmall”。他希望将天猫打造成网购领域的“第五大道”或“香榭丽舍大道”，引领中国乃至全球的B2C行业。
不过，陆兆禧败走“来往”，退居二线。选择“All in无线”的张勇，则使手机淘宝成为全球最大的移动电商平台，帮助阿里完成了从PC时代向移动时代的惊险一跃。

“我们现在需要的不是通过分析人过去的行为预测未来，而是像iPhone一样杀出一条谁都没见过的路，重新定义未来的新事物。好的东西即便没有过去，也有未来。”
马云和蔡崇信是唯二的永久合伙人.
即使马云退休了，也是“太上皇”，仍然牢牢控制着阿里。
“只要你投入了，就会有回报，只是在什么时间、以什么方式的问题。”
张勇绝对是最勤奋最投入的人之一，他每天要工作十几个小时，甚至经常超过18个小时。从前台一直干到集团CFO、菜鸟网络董事长董文红说：“我觉得自己够努力了，但我发现老逍比我还努力。”彭蕾说，阿里开高管会，从早开到晚，到最后所有人都晕头转向，只有逍遥子头脑清楚且精神饱满。
**** 马云
马云最不喜欢的就是职业经理人，卫哲就是职业经理人。这也是阿里不同于腾讯、不同于西方国家公司的一个表征。
“运营过企业的人都知道，天下没有一个制度是完美的，没有一个人是完美的，制度跟人是配套的。我面临的这种状况是制度没办法完善的。这里涉及到公司的治理问题。为什么我一直说公司需要领导者而不是职业经理人？在大是大非面前，职业经理人按照规则走就行了，领导者就必须承担责任。”
与卫哲相比，张勇就是那种既有职业精神，又能在关键时刻站出来承担责任的人，这就是马云想要的那种领导者、传承者。
*** 1811
阿里云营收占7%, 未来将是主业务
人工智能就是有更强的算力，发力芯片是对的
传统的计算机运算能力提供商Oracle、IBM、SAP、惠普、DELL等价值就没有未来了，中国的亚马逊非阿里、京东莫属，阿里云前景广阔。

双11增速27%, 去年39%

** 百度
** 陌陌
** 虎牙

*** 百度
*** 陌陌
*** 虎牙

** 自动化
市值用美金


* 操作
汇港币/美金 RTGS代码: 238
费用选:共同SHA即可

您好，若您是汇港币或美元，要求一卡通内有对应的港币或美元账户，比如：您汇款时选择的是港币现汇，则要求卡内有足额的港币现汇户。您可本人致电95555-2人工为您查询对应账户信息。

1.先 购汇 买美金，需要188 (购汇后就有美金or港币子账户了。不购汇未生成子账户会报子账户不存在)
2.再美金汇香港一卡通要130. 卡里要有人民币130，不然会报余额不足

银证转账不用再收手续费

购汇
https://www.futu5.com/faq/topic554

通过大众版或者专业版选择“汇香港一卡通”，一般一个工作日左右到账。

柜台申请管理添加7679卡号的网上汇款功能: 身份证+

香港一卡通转出限额是0
身份证+香港卡
尊敬的客户，您好！招商银行南京分行奥体支行。区号：025。地址：南京市兴隆大街188号。工作日储蓄营业时间：9:00-17:00。大堂电话：89687962。中文地标：兴隆街道办事处、紫金保险总部大楼。[招商银行]
** 手续费
港币购汇不用手续费
富途港币-美金互转不用手续费, 实时
汇10万人民币(港币124844)的费用是200人民币
* 知识
** 概念
**** 股权质押
质押率:某股东在股价为5元的时候质押了2000万股获得5000万现金，质押率为50%，成本线就是2.5元。

近几天360仍在下跌，可能还需要追加保证金，但它基本上已经处于无股可押的状态，毕竟监管市场中流通的股权要达到25%，360的半只脚已经迈向了深渊。
**** 平仓
把股票卖掉抵债
强制平仓:
强制平仓是指仓位持有者以外的第三人（期货交易所或期货经纪公司）强行了结仓位持有者的仓位，又称被斩仓或被砍仓。

券商一般只给两天时间，普通股东很难短期获得如此高额的现金，如果再形成高利贷，离破产也就不远了。
**** 爆仓
期货用语:
爆仓有两种情形，一种情形是指期货客户平仓了结头寸之后，还欠期货交易所钱，即达到：帐户浮动盈亏≥账户总资金,也即客户权益≤0
由于行情变化过快，投资者在没来得及追加保证金的时候，帐户上的保证金已经不能够维持原来的合约了，这种因保证金不足而被强行平仓所导致的保证金“归零”，俗称“爆仓”，“穿仓”的含义跟“爆仓”一样。

理论上，投资股票最大的亏损幅度是100%，即资金全部亏损，并且这种情况在现实中基本不会发生。
而做股指期货则有爆仓的概念，即投资者把资金全部亏损完了还不够，还欠期货公司保证金。
**** 杠杆效应
就是以小博大，用较小的资金撬动较大的资金，进而提高收益率（盈利或亏损）。
现货交易之所以有杠杆效应，就是因为其交易制度是保证金交易制度。投资者不需要支付合约价值的全额资金，只需要支付一定比例的保证金就可以交易。
杠杆倍数=1除以保证金比例
如：保证金比例是5%，莫投资者交易买入价值100万人民币的合约，只需要支付100万乘以5%=5万人民币的资金。换句话说就是用5万的保证金撬动了100万的资金。其收益就相当于放大了20倍。
**** 保证金账户
亦作：透支账户；信用账户。投资者在证券公司开设的一种账户形式。通过该账户，投资者可以用股票作抵押，按账户资产总市值的一定比例借用证券公司资金进行投资。
如果市场出现下跌，股票市值达不到抵押的最低标准，投资者必须追加保证金或抛售股票。
**** 保证金
在证券市场融资购买证券时，投资者所需缴纳的自备款。

例如某股东在股价为5元的时候质押了2000万股获得5000万现金，质押率为50%，成本线就是2.5元。当股价从5元跌到4元时，会先触碰预警线，券商为了降低风险，会要求抵押人增加保证金。
**** 债券
也是3%的利息，好处是可以每个月领取利息
**** 逆回购
央行借钱也要利息，是银行的银行，借钱叫逆回购，意思就是银行拿着之前政府和上市公司的借据，进行贷款。
**** 救市
各地政府拿着银行那借的，加上债券，凑出一万亿，开始买股票

**** 股息率
是一年的总派息额与当时市价的比例.如果连续多年年度股息率超过1年期银行存款利率，则这支股票基本可以视为收益型股票
例如两支股票，A股价为10元，B股价为20元，两家公司同样发放每股0.5元股利，则A公司5%的股息率显然要比B公司2.5%诱人。
** 股票暴跌的影响

https://www.zhihu.com/question/32128570/answer/514351651

跌然后涨回原来价格的变化:
银行: 多了政府抵押的地、公路; 从央行贷了更多的钱
政府: 少了可以抵押的地、公路; 保住了官位; 多发行了债券
公司: 不用被强行平仓了。
股民或机构: 低买高卖的赚了差距
不炒股的: 现金贬值
** 疑问
股权质押比例可以查到?
系统性金融风险蔓延? 什么情况会发生?
** 股市相关关键词
*** 预示熊市
平仓
爆仓
暴跌
*** 预示牛市
